package org.automation.locators;

import org.openqa.selenium.By;

public class OfficerPageLocators {
    public static final By settingsIcon = By.cssSelector(".topMenuSettings");
    public static final By officerUserTab = By.cssSelector("ul:nth-child(1) > li:nth-child(2) > a:nth-child(1) > span:nth-child(2)");
    public static final By visibilityOfLoader = By.cssSelector(".sk-circle12");
    public static final By officerUserList = By.cssSelector(".btn.btn-default.clearfilter");
    public static final By addNewButton = By.cssSelector("button[class='btn btn-primary btn-sm m-l-sm m-r-sm']");
    public static final By officerUserEmail = By.cssSelector("input[placeholder='Please Enter your email']");
    public static final By clickOnNewPassword = By.cssSelector("div[class='col-sm-8'] a");
    public static final By officerNewPassword = By.cssSelector("[name=\'pwd\']");
    public static final By confirmPasswordNew = By.cssSelector("[name=\'repwd\']");
    public static final By clickOnSaveButtonForPassword = By.cssSelector(".mat-focus-indicator.btn.btn-info.mat-button.mat-button-base._mat-animation-noopable");
    public static final By clickOnRole = By.cssSelector("[formcontrolname=\"role\"]");
    public static final By selectOptionEditView = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectOptionAdmin = By.cssSelector("mat-option:nth-child(3) span:nth-child(1)");
    public static final By firstNameOfOfficerUser = By.cssSelector("[formcontrolname='firstName']");
    public static final By lastNameOfOfficerUser = By.cssSelector("[formcontrolname='lastName']");
    public static final By phoneNumberOfofficerUser = By.cssSelector("[formcontrolname='phone']");
    public static final By selectOptionOfMobile = By.cssSelector("[formcontrolname=\"mobileProvider\"]");
    public static final By optionFromDropDownOfMobile = By.cssSelector("mat-option:nth-child(3) span:nth-child(1)");
    public static final By updateOptionFromDropDownOfMobile = By.cssSelector("mat-option:nth-child(4) span:nth-child(1)");
    public static final By streetOfofficerUser = By.cssSelector("[placeholder='Street']");
    public static final By cityNameOfofficerUser = By.cssSelector("[placeholder='City']");
    public static final By stateOfofficerUser = By.cssSelector("[placeholder='State']");
    public static final By zipCodeofficerUser = By.cssSelector("[placeholder='ZIP']");
    public static final By countryofficerUser = By.cssSelector("[placeholder='Country']");
    public static final By clickOnPremissionTab = By.cssSelector("div[id='mat-tab-label-1-1'] div[class='mat-tab-label-content']");
    public static final By crossDefaultMapSelectgion = By.cssSelector("i[title=\"Delete\"]");
    public static final By clickOnSelectCalendarToOpenDropDown = By.cssSelector("[formcontrolname=\"schedulers\"]");
    public static final By selectOptionFromCalendarDropdown = By.cssSelector("mat-option:nth-child(5) mat-pseudo-checkbox:nth-child(1)");
    public static final By selectUpdateOptionFromCalendarDropdown = By.cssSelector("mat-option:nth-child(4) mat-pseudo-checkbox:nth-child(1)");
    public static final By outsideElement = By.cssSelector("body");
    public static final By clickOnMapVisibilityForVehiclesAllOption = By.cssSelector("mat-checkbox[formcontrolname=\"allowAllVehicleGroups\"] div[class=\"mat-checkbox-inner-container\"]");
    public static final By clickOnMapVisibilityDropdown = By.cssSelector("[formcontrolname=\"vehicleGroups\"]");
    public static final By clickOndropdownlistToSelectVehicle = By.cssSelector("mat-option:nth-child(3) mat-pseudo-checkbox:nth-child(1)");
    public static final By clickOndropdownlistToDeSelectVehicle = By.cssSelector("mat-option:nth-child(3) mat-pseudo-checkbox:nth-child(1)");
    public static final By clickOndropdownlistToSelectUpdateVehicle = By.cssSelector("mat-option:nth-child(2) mat-pseudo-checkbox:nth-child(1)");
    public static final By clickOnNotificationTab = By.xpath("//div[contains(text(),'Notifications')]");
    public static final By clickOnJobToViewNotificationOptions = By.cssSelector("mat-expansion-panel:nth-child(1)");
    public static final By clickOnInvoiceToViewNotificationOption = By.cssSelector("mat-expansion-panel:nth-child(2)");
    public static final By clickOnEstimatesToViewNotificationOption = By.cssSelector("mat-expansion-panel:nth-child(3)");
    public static final By clickOnMobileUserToViewNotificationOption = By.cssSelector("mat-expansion-panel:nth-child(4)");
    public static final By clickOnContractsToViewNotificationOption = By.cssSelector("mat-expansion-panel:nth-child(5)");
    public static final By clickOnEquipmentToViewNotificationOption =By.cssSelector("mat-expansion-panel:nth-child(6)");
    public static final By clickOnInventoryToViewNotificationOption = By.cssSelector("mat-expansion-panel:nth-child(7)");
    public static final By clickOnVehiclesToViewNotificationOption =By.cssSelector("mat-expansion-panel:nth-child(8)");
    public static final By clickOnUserPreferenceTab = By.xpath("//div[contains(text(),'User Preferences')]");
    public static final By clickOnDropDownToSelectRedirectPage = By.cssSelector("[formcontrolname=\"defaultTab\"]");
    public static final By selectOptionFromDropDownForRedirectPageAfterLogin = By.cssSelector("mat-option:nth-child(1) span:nth-child(1)");
    public static final By selectOptionFromDropDownForUpdateRedirectPageAfterLogin = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By clickOnEstimateDropDown = By.cssSelector("[formcontrolname=\"defaultEstimateTemplateId\"]");
    public static final By clickOnEstimatelistToSelectTemplate = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By clickOnEstimatelistToSelectUpdatedTemplate = By.cssSelector("mat-option:nth-child(3) span:nth-child(1)");
    public static final By clickOnEstimateEmailTemplateDropdown = By.cssSelector("[formcontrolname=\"defaultEstimateEmailTemplateId\"]");
    public static final By selectTheEstimateEmailOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectTheUpdatedEstimateEmailOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(1) span:nth-child(1)");
    public static final By clickOnInvoiceEmailTemplateDropdown = By.cssSelector("[formcontrolname=\"defaultInvoiceEmailTemplateId\"]");
    public static final By selectTheInvoiceEmailOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(3) span:nth-child(1)");
    public static final By selectTheUpdatedInvoiceEmailOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By clickOnInvoiceReminderEmailDropdown = By.cssSelector("[formcontrolname=\"defaultInvoiceReminderEmailTemplateId\"]");
    public static final By selectTheInvoiceReminderOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectTheUpdatedInvoiceReminderOptionFromTheDropdownList = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By clickOnServiceAgreementDropdown = By.cssSelector("[formcontrolname=\"defaultServiceAgreementEmailTemplateId\"]");
    public static final By selectTheServiceAgreementOptionFromDropdown = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectUpdateTheServiceAgreementOptionFromDropdown = By.cssSelector("mat-option:nth-child(1) span:nth-child(1)");
    public static final By clickOnMembershipEmailDropdown = By.cssSelector("[formcontrolname=\"defaultMembershipEmailTemplateId\"]");
    public static final By selectTheMembershipEmailOptionFromDropdown = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectTheUpdatedMembershipEmailOptionFromDropdown = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By clickOnFormEmailDropdown = By.cssSelector("[formcontrolname=\"defaultFormEmailTemplateId\"]");
    public static final By selectTheFormEmailOptionFromDropdown = By.cssSelector("mat-option:nth-child(2) span:nth-child(1)");
    public static final By selectTheUpdatedFormEmailOptionFromDropdown = By.cssSelector("mat-option:nth-child(1) span:nth-child(1)");
    public static final By clickOnSaveButton = By.cssSelector("mat-dialog-actions button:nth-child(2)");
    public static final By SearchOfficerUser = By.xpath("//input[@class='form-control ng-untouched ng-pristine ng-valid']");
    public static final By clickOnSearchCreatedOfficerUser = By.cssSelector("tbody tr:nth-child(1) td:nth-child(2)");
    public static final By profileIcon = By.cssSelector(".dropdown .fa-user-circle");
    public static final By logoutButton = By.cssSelector("a[title='LogOut']");
}
